/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AurlC (https://sketchfab.com/waleguene)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/love-across-the-universe-403373f1836c4fadb4b1cf521e88f073
title: * Love Across the Universe *
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Universe = ({ ...props }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/universe.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.7} rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.5} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.3, 0.09, -5.15]} rotation={[-1.91, -0.06, 0.16]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.fuse}
            />
          </group>
          <group
            position={[4.65, 4.91, -2.99]}
            rotation={[-2.11, -0.47, -0.15]}
          >
            <group
              position={[0.37, 0, 0.07]}
              rotation={[-0.3, -0.63, -1.63]}
              scale={0.05}
            >
              <group position={[0, 0.04, -13.2]}>
                <mesh
                  geometry={nodes.Object_8.geometry}
                  material={materials.material}
                />
              </group>
            </group>
            <group
              position={[-0.65, 0.34, 1.15]}
              rotation={[-0.32, -0.89, -1.21]}
              scale={0.04}
            >
              <mesh
                geometry={nodes.Object_10.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.Object_11.geometry}
                material={materials["07_-_Default"]}
              />
            </group>
            <group
              position={[0.75, -0.21, -0.54]}
              rotation={[-0.3, -0.63, -1.63]}
              scale={0.05}
            >
              <mesh
                geometry={nodes.Object_13.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-0.04, 1.23, -0.45]}
              rotation={[-0.17, 1.11, -1.68]}
              scale={0.05}
            >
              <group position={[16.17, -0.16, -8.66]}>
                <mesh
                  geometry={nodes.Object_16.geometry}
                  material={materials.material}
                />
              </group>
            </group>
          </group>
          <group
            position={[0.3, 1.92, -0.25]}
            rotation={[0.36, 0.08, 1.31]}
            scale={[0.09, 0.04, 0.09]}
          >
            <group position={[-29.15, 18.93, -14.01]}>
              <mesh
                geometry={nodes.Object_19.geometry}
                material={materials.Toto}
              />
            </group>
          </group>
          <group
            position={[-0.06, -0.91, -3.5]}
            rotation={[-2.78, -0.08, 2.44]}
            scale={[0.08, 0.08, 0.07]}
          >
            <mesh
              geometry={nodes.Object_21.geometry}
              material={materials["21_-_Default"]}
            />
          </group>
          <group
            position={[1.2, -0.02, 1.17]}
            rotation={[-1.18, -0.22, 1.39]}
            scale={0.06}
          >
            <group
              position={[-3.58, 0.59, 22.67]}
              rotation={[Math.PI / 3, 0, 0]}
            >
              <mesh
                geometry={nodes.Object_24.geometry}
                material={materials["07_-_Default_0"]}
              />
            </group>
            <group position={[0, 0.25, -27.98]}>
              <mesh
                geometry={nodes.Object_26.geometry}
                material={materials["01_-_Default"]}
              />
            </group>
            <group
              position={[0, 0.25, -24.04]}
              rotation={[0, 0, -1.4]}
              scale={[0.8, 0.8, 0.5]}
            >
              <mesh
                geometry={nodes.Object_28.geometry}
                material={materials["02_-_Default"]}
              />
            </group>
            <group position={[0, 0.25, 8.43]} rotation={[0, 0, 0.17]}>
              <mesh
                geometry={nodes.Object_30.geometry}
                material={materials.RootNode}
              />
            </group>
            <group position={[-0.03, 0.21, 17.39]}>
              <mesh
                geometry={nodes.Object_32.geometry}
                material={materials["07_-_Default_0"]}
              />
            </group>
          </group>
          <group position={[-0.48, 0.64, 1.96]} rotation={[-1.22, 0.03, 0.08]}>
            <group position={[0.28, -3.18, -2.07]}>
              <mesh
                geometry={nodes.Object_35.geometry}
                material={materials.gauge}
              />
            </group>
          </group>
          <group
            position={[-0.68, -0.14, 0.7]}
            rotation={[3.13, 0.41, 2.24]}
            scale={[0.05, 0.06, 0.07]}
          >
            <group position={[-0.02, 0, 2.73]}>
              <mesh
                geometry={nodes.Object_38.geometry}
                material={materials["08_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[1.37, -0.44, 1.91]}
            rotation={[-1.1, 0.08, 1.99]}
            scale={[0.05, 0.06, 0.07]}
          >
            <group position={[26.05, 32.33, 7.03]}>
              <mesh
                geometry={nodes.Object_41.geometry}
                material={materials["08_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[0.01, -0.44, -1.09]}
            rotation={[0.35, 0.08, 1.36]}
            scale={[0.09, 0.04, 0.09]}
          >
            <group position={[-3, 28.48, -14.01]}>
              <mesh
                geometry={nodes.Object_44.geometry}
                material={materials["15_-_Default"]}
              />
            </group>
          </group>
          <group position={[0.01, -0.44, -1.09]} rotation={[-1.22, 0.03, 0.08]}>
            <group
              position={[-1.27, 1.27, -0.04]}
              rotation={[1.57, 0, 1.39]}
              scale={[0.09, 0.04, 0.09]}
            >
              <mesh
                geometry={nodes.Object_47.geometry}
                material={materials.Body}
              />
            </group>
          </group>
          <group
            position={[0.26, -0.72, 0.25]}
            rotation={[0.35, 0.08, -1.6]}
            scale={0.04}
          >
            <group position={[-0.69, 31.2, -29.21]} rotation={[0, 0, -0.23]}>
              <mesh
                geometry={nodes.Object_50.geometry}
                material={materials.Material_1458}
              />
            </group>
          </group>
          <group
            position={[0.01, 0.29, -2.29]}
            rotation={[0.35, 0.08, -1.6]}
            scale={0.04}
          >
            <group position={[-0.69, 31.2, -29.21]} rotation={[0, 0, -0.23]}>
              <mesh
                geometry={nodes.Object_53.geometry}
                material={materials["13_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[0.01, -0.44, -1.09]}
            rotation={[0.35, 0.08, 1.36]}
            scale={[0.09, 0.04, 0.09]}
          >
            <group position={[-3, 28.48, -14.01]}>
              <mesh
                geometry={nodes.Object_56.geometry}
                material={materials.Tires}
              />
              <mesh
                geometry={nodes.Object_57.geometry}
                material={materials.WheelParts}
              />
              <mesh
                geometry={nodes.Object_58.geometry}
                material={materials.General}
              />
            </group>
          </group>
          <group
            position={[1.31, -0.47, 1.99]}
            rotation={[-1.12, 0.08, 2.25]}
            scale={[0.05, 0.06, 0.07]}
          >
            <group position={[26.05, 32.33, 7.03]}>
              <mesh
                geometry={nodes.Object_61.geometry}
                material={materials["08_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[0.28, -3.26, 0.74]}
            rotation={[-0.36, -1.44, -0.97]}
            scale={0.09}
          >
            <mesh
              geometry={nodes.Object_63.geometry}
              material={materials["19_-_Default"]}
            />
          </group>
          <group position={[1.25, 2.01, -2.8]} rotation={[-1.22, 0.03, 0.08]}>
            <group
              position={[0.63, 0.2, 0.51]}
              rotation={[2.78, 0.74, 0.92]}
              scale={[0.05, 0.06, 0.07]}
            >
              <group position={[24.39, 32.91, -1.77]}>
                <mesh
                  geometry={nodes.Object_67.geometry}
                  material={materials["08_-_Default"]}
                />
              </group>
            </group>
            <group
              position={[0.63, 0.2, 0.51]}
              rotation={[2.78, 0.74, 1.36]}
              scale={[0.05, 0.06, 0.1]}
            >
              <group position={[24.39, 32.91, -1.77]}>
                <mesh
                  geometry={nodes.Object_70.geometry}
                  material={materials["08_-_Default"]}
                />
              </group>
            </group>
            <group
              position={[0.63, 0.2, 0.51]}
              rotation={[2.78, 0.74, 1.01]}
              scale={[0.05, 0.06, 0.07]}
            >
              <group position={[24.39, 32.91, -1.77]}>
                <mesh
                  geometry={nodes.Object_73.geometry}
                  material={materials["08_-_Default"]}
                />
              </group>
            </group>
            <group
              position={[-1.09, -0.82, -0.86]}
              rotation={[-1.62, -0.35, 1.44]}
              scale={[0.05, 0.06, 0.07]}
            >
              <group position={[-0.02, 0, 2.73]}>
                <mesh
                  geometry={nodes.Object_76.geometry}
                  material={materials["08_-_Default"]}
                />
              </group>
            </group>
            <group
              position={[-1.09, -0.82, -0.86]}
              rotation={[-1.57, -0.01, 1.45]}
              scale={[0.05, 0.06, 0.07]}
            >
              <group position={[-0.02, 0, 2.73]}>
                <mesh
                  geometry={nodes.Object_79.geometry}
                  material={materials["08_-_Default"]}
                />
              </group>
            </group>
          </group>
          <group position={[-0.05, -1.78, -3.4]} rotation={[-1.22, 0.03, 0.08]}>
            <group
              position={[-0.04, -0.9, 0.04]}
              rotation={[0.3, -1.51, -1.54]}
              scale={0.09}
            >
              <mesh
                geometry={nodes.Object_82.geometry}
                material={materials["19_-_Default"]}
              />
            </group>
            <group position={[0, 0.37, 0]} rotation={[-Math.PI / 9, 0, 0]}>
              <group
                position={[-0.03, 0.22, -0.05]}
                rotation={[-1.56, 0, -3.09]}
                scale={[0.06, 0.06, 0.05]}
              >
                <group position={[-20.81, -11.77, -2.75]}>
                  <mesh
                    geometry={nodes.Object_86.geometry}
                    material={materials.Material_1411}
                  />
                </group>
              </group>
              <group
                position={[1.7, -0.65, -1.16]}
                rotation={[-1.56, 0, 2.02]}
                scale={[0.09, 0.08, 0.07]}
              >
                <mesh
                  geometry={nodes.Object_88.geometry}
                  material={materials.Town}
                />
              </group>
            </group>
          </group>
          <group
            position={[0.21, -2.85, -0.47]}
            rotation={[-Math.PI / 2, 0, 0.09]}
          >
            <group
              position={[-0.03, 0.22, -0.05]}
              rotation={[-1.56, 0, -3.09]}
              scale={[0.06, 0.06, 0.05]}
            >
              <group position={[-20.81, -11.77, -2.75]}>
                <mesh
                  geometry={nodes.Object_92.geometry}
                  material={materials.Material_1411}
                />
              </group>
            </group>
            <group
              position={[1.7, -0.65, -1.16]}
              rotation={[-1.56, 0, 2.02]}
              scale={[0.09, 0.08, 0.07]}
            >
              <mesh
                geometry={nodes.Object_94.geometry}
                material={materials.Town}
              />
            </group>
          </group>
          <group
            position={[-14.22, -3.99, -1.54]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.42, -0.22, 0.08]}
              rotation={[-2.73, 0.24, -3.09]}
              scale={[0.89, 0.56, 0.56]}
            >
              <mesh
                geometry={nodes.Object_97.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-9.5, -2.78, 2.05]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[0.05, 0.06, 0.37]}
              rotation={[2.72, -0.84, -2.77]}
              scale={[0.5, 0.5, 0.79]}
            >
              <mesh
                geometry={nodes.Object_100.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-10.06, -3.01, 1.84]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.24, 0.25, 0.18]}
              rotation={[1.84, -0.25, -3]}
              scale={[0.78, 0.49, 0.49]}
            >
              <mesh
                geometry={nodes.Object_103.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-10.62, -3.22, 1.62]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.25, 0.28, 0.21]}
              rotation={[1.85, -0.29, -2.99]}
              scale={[0.86, 0.54, 0.54]}
            >
              <mesh
                geometry={nodes.Object_106.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-11.17, -3.42, 1.37]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.47, -0.04, 0.28]}
              rotation={[3.02, 0.02, -2.76]}
              scale={[1.04, 0.66, 0.66]}
            >
              <mesh
                geometry={nodes.Object_109.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-13.86, -3.51, -5.74]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.71, 0.32, -0.34]}
              rotation={[2.66, 1.27, -1.47]}
              scale={[0.78, 0.78, 1.23]}
            >
              <mesh
                geometry={nodes.Object_112.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-14.22, -3.75, -4.34]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.5, 0.19, -0.21]}
              rotation={[2.94, 1.25, -1.76]}
              scale={[0.52, 0.52, 0.82]}
            >
              <mesh
                geometry={nodes.Object_115.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-11.7, -3.59, 1.1]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.01, 0.09, 0.26]}
              rotation={[2.06, -0.36, 2.71]}
              scale={[0.38, 0.61, 0.38]}
            >
              <mesh
                geometry={nodes.Object_118.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-12.18, -3.74, 0.78]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.49, -0.07, 0.14]}
              rotation={[-2.93, 0.22, -2.67]}
              scale={[0.89, 0.56, 0.56]}
            >
              <mesh
                geometry={nodes.Object_121.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-14, -3.59, -5.28]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-1.29, 0.56, -0.6]}
              rotation={[2.75, 1.26, -1.56]}
              scale={[1.4, 1.4, 2.21]}
            >
              <mesh
                geometry={nodes.Object_124.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-14.12, -3.68, -4.81]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-1.32, 0.54, -0.59]}
              rotation={[2.84, 1.26, -1.66]}
              scale={[1.4, 1.4, 2.21]}
            >
              <mesh
                geometry={nodes.Object_127.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-13.35, -3.21, -7.12]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.57, 0.28, -0.3]}
              rotation={[2.45, 1.26, -1.26]}
              scale={[0.65, 0.65, 1.03]}
            >
              <mesh
                geometry={nodes.Object_130.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-13.15, -3.1, -7.58]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.56, 0.29, -0.3]}
              rotation={[2.39, 1.26, -1.2]}
              scale={[0.65, 0.65, 1.03]}
            >
              <mesh
                geometry={nodes.Object_133.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-14.3, -3.82, -3.87]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.53, -0.03, -0.17]}
              rotation={[-2.52, 0.93, -2.94]}
              scale={[0.82, 0.52, 0.52]}
            >
              <mesh
                geometry={nodes.Object_136.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-14.36, -3.88, -3.4]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.99, -0.36, -1.08]}
              rotation={[-1.45, 0.91, 2.16]}
              scale={[1.7, 1.7, 2.69]}
            >
              <mesh
                geometry={nodes.Object_139.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-14.38, -3.92, -2.93]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.97, 0.3, -0.35]}
              rotation={[-3.04, 1.18, -2.08]}
              scale={[0.95, 0.95, 1.5]}
            >
              <mesh
                geometry={nodes.Object_142.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-14.36, -3.96, -2.46]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.98, 0.27, -0.33]}
              rotation={[-2.95, 1.14, -2.18]}
              scale={[0.95, 0.95, 1.5]}
            >
              <mesh
                geometry={nodes.Object_145.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-14.31, -3.98, -2]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-1, 0.24, -0.31]}
              rotation={[-2.87, 1.09, -2.27]}
              scale={[0.95, 0.95, 1.5]}
            >
              <mesh
                geometry={nodes.Object_148.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-12.62, -3.82, 0.42]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.03, -0.05, 0.41]}
              rotation={[-2.92, -0.69, -2.32]}
              scale={[0.56, 0.56, 0.89]}
            >
              <mesh
                geometry={nodes.Object_151.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-14.06, -3.97, -1.1]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.62, 0.08, -0.13]}
              rotation={[-2.73, 0.91, -2.44]}
              scale={[0.89, 0.56, 0.56]}
            >
              <mesh
                geometry={nodes.Object_154.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-13.81, -3.94, -0.68]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.62, 0.04, -0.08]}
              rotation={[-2.71, 0.76, -2.49]}
              scale={[0.89, 0.56, 0.56]}
            >
              <mesh
                geometry={nodes.Object_157.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-13.47, -3.89, -0.29]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.36, -0.22, 0.15]}
              rotation={[-2.35, -0.09, -2.61]}
              scale={[0.89, 0.56, 0.56]}
            >
              <mesh
                geometry={nodes.Object_160.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-13.06, -3.85, 0.06]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.4, -0.2, 0.14]}
              rotation={[-3.03, 0.29, 3.1]}
              scale={[0.89, 0.56, 0.56]}
            >
              <mesh
                geometry={nodes.Object_163.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-8.94, -2.54, 2.25]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.28, 0.08, 0.22]}
              rotation={[2.43, -0.05, -2.93]}
              scale={[0.7, 0.44, 0.44]}
            >
              <mesh
                geometry={nodes.Object_166.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-13.7, -3.41, -6.2]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-1.57, 0.74, -0.78]}
              rotation={[2.58, 1.26, -1.39]}
              scale={[1.76, 1.76, 2.79]}
            >
              <mesh
                geometry={nodes.Object_169.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-6.74, -1.85, 2.35]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.01, 0.16, 0.33]}
              rotation={[1.83, 0.01, 2.33]}
              scale={[0.51, 0.81, 0.51]}
            >
              <mesh
                geometry={nodes.Object_172.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-7.39, -2.09, 2.3]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.29, 0.27, 0.14]}
              rotation={[1.5, 0, 3.05]}
              scale={[0.78, 0.49, 0.49]}
            >
              <mesh
                geometry={nodes.Object_175.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-8.03, -2.33, 2.21]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.36, 0.33, -0.15]}
              rotation={[0.56, 0.02, 3.05]}
              scale={[0.83, 0.52, 0.52]}
            >
              <mesh
                geometry={nodes.Object_178.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-13.53, -3.31, -6.66]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-1.79, 0.4, -0.75]}
              rotation={[-2.34, 1.21, -2.69]}
              scale={[1.76, 1.76, 2.79]}
            >
              <mesh
                geometry={nodes.Object_181.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-9.2, -2.34, 2.48]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.07, 0.25, 0.39]}
              rotation={[1.78, -0.11, 2.55]}
              scale={[0.66, 1.04, 0.66]}
            >
              <mesh
                geometry={nodes.Object_184.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-12.57, -2.87, -8.33]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-1.8, 1.44, 0.06]}
              rotation={[2.71, 0.4, -1.49]}
              scale={[2.4, 3.81, 2.4]}
            >
              <mesh
                geometry={nodes.Object_187.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-12.34, -2.75, -8.77]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.66, 0.54, 0.02]}
              rotation={[2.7, 0.4, -1.47]}
              scale={[0.89, 1.41, 0.89]}
            >
              <mesh
                geometry={nodes.Object_190.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-12.1, -2.63, -9.22]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.65, 0.54, 0.01]}
              rotation={[2.7, 0.4, -1.45]}
              scale={[0.89, 1.41, 0.89]}
            >
              <mesh
                geometry={nodes.Object_193.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-12.79, -2.99, -7.88]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.47, 1.68, 0.45]}
              rotation={[2.73, 0.4, -0.73]}
              scale={[2.4, 3.81, 2.4]}
            >
              <mesh
                geometry={nodes.Object_196.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-5.43, -1.37, 2.39]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.19, 0.09, 0.2]}
              rotation={[2.07, 0.05, 2.95]}
              scale={[0.59, 0.37, 0.37]}
            >
              <mesh
                geometry={nodes.Object_199.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-6.08, -1.61, 2.38]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.25, 0.16, 0.2]}
              rotation={[1.82, 0.06, 3]}
              scale={[0.7, 0.44, 0.44]}
            >
              <mesh
                geometry={nodes.Object_202.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-4.77, -1.12, 2.38]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.18, 0.26, -0.08]}
              rotation={[0.48, 0.23, 2.53]}
              scale={[0.59, 0.37, 0.37]}
            >
              <mesh
                geometry={nodes.Object_205.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-3.13, -0.39, 2.5]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.17, 0.13, -0.17]}
              rotation={[1.62, 0.92, -0.69]}
              scale={[0.29, 0.29, 0.46]}
            >
              <mesh
                geometry={nodes.Object_208.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-4.11, -0.87, 2.34]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.2, 0.13, 0.08]}
              rotation={[1.46, 0.24, 2.99]}
              scale={[0.46, 0.29, 0.29]}
            >
              <mesh
                geometry={nodes.Object_211.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-3.46, -0.62, 2.28]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.27, 0.14, -0.08]}
              rotation={[0.46, 0.28, -3]}
              scale={[0.46, 0.29, 0.29]}
            >
              <mesh
                geometry={nodes.Object_214.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-2.81, -0.37, 2.21]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.21, 0.13, 0.08]}
              rotation={[1.46, 0.31, 2.98]}
              scale={[0.46, 0.29, 0.29]}
            >
              <mesh
                geometry={nodes.Object_217.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
          <group
            position={[-2.17, -0.12, 2.12]}
            rotation={[-1.19, -0.4, 0.09]}
            scale={[0.65, 1, 1]}
          >
            <group
              position={[-0.21, 0.12, 0.09]}
              rotation={[1.46, 0.34, 2.97]}
              scale={[0.46, 0.29, 0.29]}
            >
              <mesh
                geometry={nodes.Object_220.geometry}
                material={materials.bubbles}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/universe.gltf");
